# ~/miniapi/pyproject.toml

[tool.pytest.ini_options]
# Adiciona o diret√≥rio atual (raiz do projeto) ao PYTHONPATH
# Isso permite que os testes importem 'src.core.exchange_service' corretamente.
pythonpath = [
    "."
]